/**
 * S5 — Honest connector matrix vs Fivetran / Hevo (India GTM).
 */

export const CONNECTOR_MATRIX = {
  updatedAt: '2026-08-27',
  disclaimer:
    'Que wins post-ingest stewardship — not connector count. Fivetran leads breadth; Que leads cert KPI + joins + Monk after load.',
  competitors: ['que', 'fivetran', 'hevo'],
  rows: [
    {
      id: 'connector_count',
      category: 'Breadth',
      label: 'Pre-built connectors',
      que: '12 live + spreadsheet (depth > count)',
      fivetran: '700+',
      hevo: '150+',
      queDepth: 'partial',
      indiaNote: 'Stack Que on Hevo/Fivetran for India mid-market — don’t rip replace day 1.',
    },
    {
      id: 'salesforce',
      category: 'CRM',
      label: 'Salesforce',
      que: 'Live describe + incremental samples + field map',
      fivetran: 'Full object replication',
      hevo: 'Standard SF connector',
      queDepth: 'strong',
      indiaNote: 'Every India SaaS/services firm — Que maps CRM to packs after sync.',
    },
    {
      id: 'bigquery',
      category: 'Warehouse',
      label: 'BigQuery',
      que: 'INFORMATION_SCHEMA + liveExec + query-history joins',
      fivetran: 'Native BQ destination',
      hevo: 'Native BQ destination',
      queDepth: 'strong',
      indiaNote: 'GCP-heavy startups — Que reads BQ you already loaded via Hevo.',
    },
    {
      id: 'postgres',
      category: 'Database',
      label: 'Postgres',
      que: 'Live introspect + CDC doc + replica pipeline',
      fivetran: 'Logical replication / CDC',
      hevo: 'CDC',
      queDepth: 'strong',
      indiaNote: 'Replace fragile glue scripts with graph-first onboarding.',
    },
    {
      id: 'join_infer',
      category: 'Intelligence',
      label: 'Join inference',
      que: 'Cross-source + BQ/DBx/SF query history',
      fivetran: 'None (use dbt)',
      hevo: 'Limited',
      queDepth: 'differentiator',
    },
    {
      id: 'cert_kpi',
      category: 'Governance',
      label: 'Certified KPI loop',
      que: 'Monk → golden eval → Report Studio → BI ship',
      fivetran: 'None',
      hevo: 'None',
      queDepth: 'differentiator',
    },
    {
      id: 'ceo_chat',
      category: 'Self-serve',
      label: 'CEO chat on certified marts',
      que: 'Cert-only guardrail',
      fivetran: 'N/A',
      hevo: 'N/A',
      queDepth: 'differentiator',
    },
    {
      id: 'dbt_exit',
      category: 'Exit',
      label: 'dbt bundle export',
      que: 'v2 workspace bundle + tests',
      fivetran: 'Partner dbt',
      hevo: 'Limited',
      queDepth: 'strong',
    },
    {
      id: 'pricing_india',
      category: 'GTM',
      label: 'India mid-market land',
      que: '₹50k–80k/mo + sandbox',
      fivetran: 'USD enterprise',
      hevo: 'INR tiers',
      queDepth: 'strong',
    },
    {
      id: 'razorpay',
      category: 'India commerce',
      label: 'Razorpay / Zoho / Shopify',
      que: 'Fixture sync + join infer (S9) — stack on Hevo for ingest',
      fivetran: 'Varies',
      hevo: 'Shopify common',
      queDepth: 'fixture',
      indiaNote: 'India D2C: Shopify orders + Razorpay payments + Zoho invoices in one graph.',
    },
  ],
  queConnectors: [
    { id: 'postgresql', name: 'PostgreSQL', depth: 'P1', live: true, incremental: 'CDC doc' },
    { id: 'bigquery', name: 'BigQuery', depth: 'P0', live: true, incremental: 'Query history joins' },
    { id: 'salesforce', name: 'Salesforce', depth: 'P0', live: true, incremental: 'SystemModstamp' },
    { id: 'databricks', name: 'Databricks', depth: 'P1', live: true, incremental: 'Query history joins' },
    { id: 'snowflake', name: 'Snowflake', depth: 'P1', live: true, incremental: 'Query history joins' },
    { id: 'mongodb', name: 'MongoDB', depth: 'P1', live: true, incremental: 'Schema sync' },
    { id: 'shopify', name: 'Shopify', depth: 'S9', live: true, incremental: 'Fixture + webhook doc' },
    { id: 'razorpay', name: 'Razorpay', depth: 'S9', live: true, incremental: 'Fixture' },
    { id: 'zoho', name: 'Zoho Books', depth: 'S9', live: true, incremental: 'Fixture' },
    { id: 'excel', name: 'Excel / CSV', depth: 'P1', live: true, incremental: 'Re-upload' },
    { id: 'spreadsheet', name: 'Spreadsheet', depth: 'P1', live: true, incremental: 'Re-upload' },
  ],
}

export function getConnectorMatrix() {
  return CONNECTOR_MATRIX
}
